[package]
name = "sudoku-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[lib]
name = "sudoku_rs"
path = "src/lib.rs"

[[bin]]
name = "sudoku_solver"
path = "src/bin.rs"